#include<iostream>
using namespace std;
// Name Umair Hassan Roll No 24i3137 SE(C)
int main(){
int a =10,b=7,sum,sub,mul;
float div;
sum=a+b;
sub=a-b;
cout<<"               Before Increment          ";
cout<<"\n";
cout<<"Number 1  : "<<a;
cout<<"\n";
cout<<"Number 2  : "<<b;
cout<<"\n";
cout<<"Adiition : "<<sum;
cout<<"\n";
cout<<"Subtraction : "<<sub;
cout<<"\n";
cout<<"               After Pre Increment          ";
b=++a;
cout<<"\n";
cout<<"Number 1  : "<<a;
cout<<"\n";
cout<<"Number 2  : "<<b;
cout<<"\n";
sum=a=b;

cout<<"Adiition : "<<sum;
cout<<"\n";
sub=a-b;
cout<<"Subtraction : "<<sub;
cout<<"\n";

cout<<"               Before Post Increment          ";
cout<<"\n";
cout<<"Number 1  : "<<a;
cout<<"\n";
cout<<"Number 2  : "<<b;
cout<<"\n";
mul=a*b;
cout<<"Producct is : "<<mul;
cout<<"\n";
cout<<"               After Post Increment          ";
cout<<"\n";
b=a++;
cout<<"Number 1  : "<<a;
cout<<"\n";
cout<<"Number 2  : "<<b;

cout<<"\n";
mul=a*b;
cout<<"Producct is : "<<mul;
cout<<"\n";
cout<<"               Before Decrement       ";
cout<<"\n";
cout<<"Number 1  : "<<a;
cout<<"\n";
cout<<"Number 2  : "<<b;
cout<<"\n";
sub=a-b;
cout<<"Subtraction : "<<sub;
cout<<"\n";
cout<<"               After --a Dencrement          ";
cout<<"\n";
b=--a;
cout<<"Number 1  : "<<a;
cout<<"\n";
cout<<"Number 2  : "<<b;
cout<<"\n";
sub=a-b;
cout<<"Subtraction : "<<sub;
cout<<"\n";
cout<<"               Before Decement         ";
cout<<"\n";
cout<<"Number 1  : "<<a;
cout<<"\n";
cout<<"Number 2  : "<<b;
cout<<"\n";
div=a/b;
cout<<"Divison : "<<div;
cout<<"\n";
cout<<"               After a-- decrement          ";
cout<<"\n";
b=a--;
cout<<"Number 1  : "<<a;
cout<<"\n";
cout<<"Number 2  : "<<b;
cout<<"\n";
div=a/b;
cout<<"Divison : "<<div;
cout<<"\n";
cout<<"                 Perform Operations       ";
cout<<"\n";
cout<<"Number 1  : "<<a;
cout<<"\n";
cout<<"Number 2  : "<<b;
cout<<"\n";
sum=++a-b--;
sub=b++ - --a;
mul=a++*--b;
div=++a/b--;
cout<<"Sum of ++a and b--:"<<sum;
cout<<"\n";
cout<<"Subtraction of --a from b++ : "<<sub;

cout<<"\n";
cout<<"Multiplication a++ with --b :  "<<mul;
cout<<"\n";
cout<<"Divison ++a by b-- :  "<<div;
cout<<"\n";
return 0;

}
